import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
// import "../globals.css";
import Header from "@/components/Header";
import Provider from "@/components/SiginButton/Provider";
import StoreProvider from "../StoreProvider";
import { cn } from "@/lib/utils";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <StoreProvider>
          <Provider>
            <Header />
            {children}
          </Provider>
        </StoreProvider>
      </body>
    </html>
  );
}
